# Site settings
gems:
  - jekyll-sitemap
url: http://savchook.com
default_lang: uk
title: Видавець Савчук О. О.
menu:
  about-publishers: Про видавництво
  how-to-publish: Як видати книгу?
  books: Книгарня
  accessories: Аксесуари
  buy-book: Як придбати?
  contacts: Контакти
collections:
  news:
    output: false
  books:
    output: true
  accessories:
    output: true

# Build settings
exclude: [Gemfile, Gemfile.lock]
sass:
  style: :compressed
